"""
SynthesizedAnswer data model for AI-generated answers.
"""

import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import List, Dict, Any, Optional

logger = logging.getLogger(__name__)


class SynthesisMethod(str, Enum):
    """Method used to synthesize the answer."""
    EVIDENCE_BASED = "EVIDENCE_BASED"  # Direct evidence in transcript
    INFERENCE = "INFERENCE"  # Logical inference from context
    BEST_PRACTICE = "BEST_PRACTICE"  # AWS best practice applied
    FALLBACK = "FALLBACK"  # Minimal context, low confidence


@dataclass
class EvidenceQuote:
    """Evidence quote from transcript supporting the answer."""
    text: str
    location: str  # e.g., "transcript:line:87"
    relevance: str  # Explanation of why this quote is relevant


@dataclass
class SynthesizedAnswer:
    """
    AI-synthesized answer for a gap WAFR question.
    
    This represents an answer generated by the Answer Synthesis Agent
    (enhanced InferenceAgent) that requires human review and validation.
    """
    # Identity (required fields)
    question_id: str
    pillar: str  # SEC, REL, PERF, COST, OPS, SUS
    question_text: str
    synthesized_answer: str  # Required field
    
    # Optional fields with defaults
    criticality: str = "MEDIUM"  # HIGH, MEDIUM, LOW
    reasoning_chain: List[str] = field(default_factory=list)
    assumptions: List[str] = field(default_factory=list)
    
    # Confidence
    confidence: float = 0.5  # 0.0 - 1.0
    confidence_justification: str = ""
    synthesis_method: SynthesisMethod = SynthesisMethod.INFERENCE
    
    # Evidence
    evidence_quotes: List[EvidenceQuote] = field(default_factory=list)
    related_insights: List[str] = field(default_factory=list)  # Insight IDs
    
    # Review Guidance
    requires_attention: List[str] = field(default_factory=list)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "question_id": self.question_id,
            "pillar": self.pillar,
            "question_text": self.question_text,
            "criticality": self.criticality,
            "synthesized_answer": self.synthesized_answer,
            "reasoning_chain": self.reasoning_chain,
            "assumptions": self.assumptions,
            "confidence": self.confidence,
            "confidence_justification": self.confidence_justification,
            "synthesis_method": self.synthesis_method.value,
            "evidence_quotes": [
                {
                    "text": eq.text,
                    "location": eq.location,
                    "relevance": eq.relevance
                }
                for eq in self.evidence_quotes
            ],
            "related_insights": self.related_insights,
            "requires_attention": self.requires_attention,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SynthesizedAnswer":
        """Create from dictionary."""
        # Normalize evidence_quotes - handle both string and dict formats
        evidence_quotes_raw = data.get("evidence_quotes", [])
        evidence_quotes = []
        for eq in evidence_quotes_raw:
            if isinstance(eq, str):
                # Convert string to dict format
                evidence_quotes.append(EvidenceQuote(
                    text=eq,
                    location="",
                    relevance=""
                ))
            elif isinstance(eq, dict):
                # Already a dict, use it directly
                evidence_quotes.append(EvidenceQuote(
                    text=eq.get("text", ""),
                    location=eq.get("location", ""),
                    relevance=eq.get("relevance", "")
                ))
            else:
                # Skip invalid types
                continue
        
        # Handle synthesis_method with mapping for invalid values
        synthesis_method_str = data.get("synthesis_method", "INFERENCE")
        
        # Map common invalid values to valid enum values
        method_mapping = {
            "transcript_direct": "EVIDENCE_BASED",  # Direct from transcript = evidence-based
            "TRANSCRIPT_DIRECT": "EVIDENCE_BASED",
            "direct": "EVIDENCE_BASED",
            "DIRECT": "EVIDENCE_BASED",
            "user_input": "INFERENCE",
            "USER_INPUT": "INFERENCE",
        }
        
        # Apply mapping if needed
        if synthesis_method_str in method_mapping:
            synthesis_method_str = method_mapping[synthesis_method_str]
        
        # Try to create enum, fallback to INFERENCE if invalid
        try:
            synthesis_method = SynthesisMethod(synthesis_method_str)
        except ValueError:
            # Invalid enum value, use INFERENCE as default
            logger.warning(f"Invalid synthesis_method '{synthesis_method_str}', using INFERENCE")
            synthesis_method = SynthesisMethod.INFERENCE
        
        return cls(
            question_id=data["question_id"],
            pillar=data.get("pillar", ""),
            question_text=data.get("question_text", ""),
            criticality=data.get("criticality", "MEDIUM"),
            synthesized_answer=data["synthesized_answer"],
            reasoning_chain=data.get("reasoning_chain", []),
            assumptions=data.get("assumptions", []),
            confidence=data.get("confidence", 0.5),
            confidence_justification=data.get("confidence_justification", ""),
            synthesis_method=synthesis_method,
            evidence_quotes=evidence_quotes,
            related_insights=data.get("related_insights", []),
            requires_attention=data.get("requires_attention", []),
        )

